### PR TITLE
Change schema.rb directory to db_denorm

### PR DESCRIPTION
**Pull request by mykoweb**
This branch is branched off the `1.0.2` release tag.

### CODE REVIEW

**Comment by bradrobertson** [comment]
can you suggest why we'd want to do this?

**Comment by mykoweb** [comment]
Sorry. I accidentally opened this. Closing.

**Comment by mykoweb** [comment]
Hi @bradrobertson 

I can, but I'll do so when I have a proper PR set up. Does that work for you?

Thanks,

Mike

**Comment by bradrobertson** [comment]
Sure whenever everything is put together.

**Pull request closed without merging**
