### PR TITLE
Works with Rails 5

### PR DESCRIPTION
**Pull request by GCorbel**
Resolve the issue #331

### CODE REVIEW

**Comment by holidayworking** [comment]
I think #295 and #300 art not resolved.

**Comment by holidayworking** [comment]
I run spec on Rails 5.

```
Finished in 1 minute 11.57 seconds (files took 2.88 seconds to load)
226 examples, 19 failures

Failed examples:

rspec ./spec/adapters/mysql2_adapter_spec.rb:35 # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas #init should process model exclusions
rspec './spec/adapters/mysql2_adapter_spec.rb[1:1:1:5:1]' # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas it should behave like a generic apartment adapter #process is deprecated
rspec './spec/adapters/mysql2_adapter_spec.rb[1:1:1:7:1]' # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas it should behave like a generic apartment adapter #current should return the current db name
rspec './spec/adapters/mysql2_adapter_spec.rb[1:1:1:1:1]' # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas it should behave like a generic apartment adapter #create should create the new databases
rspec './spec/adapters/mysql2_adapter_spec.rb[1:1:1:1:2]' # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas it should behave like a generic apartment adapter #create should load schema.rb to new schema
rspec './spec/adapters/mysql2_adapter_spec.rb[1:1:1:1:3]' # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas it should behave like a generic apartment adapter #create should yield to block if passed and reset
rspec './spec/adapters/mysql2_adapter_spec.rb[1:1:1:3:2]' # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas it should behave like a generic apartment adapter #switch! should reset connection if database is nil
rspec './spec/adapters/mysql2_adapter_spec.rb[1:1:1:3:3]' # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas it should behave like a generic apartment adapter #switch! should raise an error if database is invalid
rspec './spec/adapters/mysql2_adapter_spec.rb[1:1:1:3:1]' # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas it should behave like a generic apartment adapter #switch! should connect to new db
rspec './spec/adapters/mysql2_adapter_spec.rb[1:1:1:8:1]' # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas it should behave like a generic apartment adapter #each iterates over each tenant by default
rspec './spec/adapters/mysql2_adapter_spec.rb[1:1:1:8:2]' # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas it should behave like a generic apartment adapter #each iterates over the given tenants
rspec './spec/adapters/mysql2_adapter_spec.rb[1:1:1:2:1]' # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas it should behave like a generic apartment adapter #drop should remove the db
rspec './spec/adapters/mysql2_adapter_spec.rb[1:1:1:6:1]' # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas it should behave like a generic apartment adapter #reset should reset connection
rspec './spec/adapters/mysql2_adapter_spec.rb[1:1:1:4:1]' # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas it should behave like a generic apartment adapter #switch connects and resets the tenant
rspec './spec/adapters/mysql2_adapter_spec.rb[1:1:1:4:3]' # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas it should behave like a generic apartment adapter #switch warns if no block is given, but calls switch!
rspec './spec/adapters/mysql2_adapter_spec.rb[1:1:1:4:2]' # Apartment::Adapters::Mysql2Adapter using - the equivalent of - schemas it should behave like a generic apartment adapter #switch should not throw exception if current is no longer accessible
rspec ./spec/integration/query_caching_spec.rb:27 # query caching clears the ActiveRecord::QueryCache after switching databases
rspec ./spec/tenant_spec.rb:47 # Apartment::Tenant using mysql with prefix and schemas #create should create a new database
rspec ./spec/tenant_spec.rb:140 # Apartment::Tenant using postgresql with schemas #switch! with excluded models should create excluded models in public schema
```

**Comment by GCorbel** [comment]
I tried with postgres and it works. I do not have the time to try to resolve issues for mysql right now. We can close this PR or create a new branch for Rails 5. What you think?

**Comment by holidayworking** [comment]
I maybe resolved issues for MySQL. Therefore I created a new PR #333.

**Comment by bradrobertson** [comment]
Let's close this and work on #333 and get the test suite green then we're good to go.

**Pull request closed without merging**
