### PR TITLE
enhance db:drop task

### PR DESCRIPTION
**Pull request by kuzukuzu**
Implement of https://github.com/influitive/apartment/issues/464 .

### CODE REVIEW

**Comment by kuzukuzu** [comment]
add and fix tests later.

**Comment by kuzukuzu** [comment]
now test added.

**Comment by mikecmpbll** [comment]
awesome! quick question—what's the reason for the different dependency order for the drop task? why must it run before the normal drop task?

**Comment by kuzukuzu** [comment]
The answer is simple.

After the normal drop task, public tenant has been cleaned up.
It means that `Apartment.tenant_names` might not returns correct tenants list.

So, we should run the extra drop task before the original one.

**Comment by mikecmpbll** [comment]
perfect, thanks :D.

**Pull request merged**
