### PR TITLE
Ignore `CREATE SCHEMA public` statement in pg dump

### LINKED ISSUE #581: Rails 5.2.2 + Apartment Gem 2.2.0 - Error: 'One of the following schema(s) is invalid'
## Steps to reproduce
rake db:drop
rake db:create
rake db:migrate

## Expected behavior
Public schema should be created and migrations run
Tenant schemas should be created and migrations run

## Actual behavior
Public schema is created and all migrations successfully run
Tenant scheams are NOT created and migrations are NOT run on tenant schemas

Error:
    Migrating zenith tenant
    One of the following schema(s) is invalid: "zenith" "public"
    Migrating myotherapy tenant
    One of the following schema(s) is invalid: "myotherapy" "public"

It appears as though the Apartment gem tries to recreate the "public" schema each time it tries to create a tenant schema is failing because the "public" schema already exists. That is my guess at least, no idea what would cause this to happen. 

## System configuration

Gem Versions:
pg 1.1.4 or 0.21.0 (tried both)

Application Config: Subdomain
config.middleware.use Apartment::Elevators::Subdomain

* Database: (Tell us what database and its version you use.)
Tried using PostgreSQL versions 9, 10, and 11 using the Postgres.app on OS X

* Apartment version:
apartment 2.2.0

* Apartment config (in `config/initializers/apartment.rb` or so):
Apartment Config: Subdomain
config.excluded_models = %w{ Clinic }
config.tenant_names = ['zenith', 'myotherapy']
(everything else left at defaults)

  * `use_schemas`: (`true` or `false`)
Default: true

* Rails (or ActiveRecord) version:
Rails 5.2.2

* Ruby version:
Ruby 2.6.1

### PR DESCRIPTION
**Pull request by artemave**
Fixes https://github.com/influitive/apartment/issues/581

### CODE REVIEW

**Comment by tfwright** [comment]
As far as I can tell this is blocking using apartment on Heroku, since their environment seems to always use pg_dump  from version 11. Would be really nice to see this merged, if anyone is still maintaining this.

**Comment by mjfrey** [comment]
I am also blocked in Heroku -- is someone going to merge this?

**Comment by danielolivaresd** [comment]
Thanks for this. As a future reference (and for other ones having issues), this PR allows me to use schemas instead of separate DB connections *and* use UUID primary keys (e.g. using the following schema) with Postgres 11. Previously we had to opt for separate databases but we think that there are some threading issues with that approach. Anyway, it works now with the following setup:

```ruby
# schema.rb
create_table "foos", id: :uuid, default: -> { "gen_random_uuid()" }, #...
```

My Apartment config looks like this:
```ruby
# apartment.rb
Apartment.configure do |config|
  config.use_schemas = true
  config.use_sql = true
  config.pg_excluded_names = ["uuid_generate_v4", "gen_random_uuid"]
end
```

Are there any plans to release a new version of the gem that includes this and other recent PRs soon?

**Comment by mikecmpbll** [comment]
@K1N5L4Y3R yep i'll cut the release in the next couple of days just want to work through the rest of the backlog first see if there's any other low hanging fruit

**Comment by danielolivaresd** [comment]
Hey @mikecmpbll , thanks for your answer. This is a kind reminder about the release. Anything I or the community can do to help to expedite it?

**Comment by mikecmpbll** [comment]
whoops done as 2.2.1 :)

**Pull request merged**
