### PR TITLE
Support Rails 5.1

### PR DESCRIPTION
**Pull request by meganemura**
Support Ruby on Rails 5.1.
This is the successor of #417 and #426.

### CODE REVIEW

**Comment by meganemura** [comment]
[Failed test](https://travis-ci.org/influitive/apartment/jobs/250325634) is reproduced locally. I will find out why.

**Comment by meganemura** [comment]
As I described in commit message, the test is failed because of the side effect ocurred in loading dummy app. I think the test will be passed next time with new commits...

I modified an RSpec option for pinning order of examples to clarify that the fix is working. Please feel free to remove or comment out it.

**Comment by mikecmpbll** [comment]
👌

**Comment by meganemura** [comment]
thanks 🍤

**Comment by kalv** [comment]
@mikecmpbll When are you going to be releasing a gem for the Rails 5.x support? Anything we can do to help?

**Comment by mikecmpbll** [comment]
i don't _think_ there's anything broken with the currently released version and Rails 5.1, but there's a host of bugfixes in general that have gone in since last release so I should probably cut a new one.

will get on it now.

**Comment by mikecmpbll** [comment]
whups, forgot to ask @bradrobertson to add me on rubygems. it's `gem owner apartment --add mike@wordofmike.net` if you read this :).

went up a major to 2.0.0 because of the removal of the deprecations. (also we missed a deprecation on tld_length, oops :))

**Comment by kalv** [comment]
Thanks for bumping a new version! 💯

**Comment by mikecmpbll** [comment]
released

**Pull request merged**
