### PR TITLE
Mysql2 Adapter doesn't escape tenant during drop

### PR DESCRIPTION
**Pull request by ironiqu**
#131

Even if database name is a Numbers, this SQL runs.

### CODE REVIEW

**Comment by mikecmpbll** [comment]
i noticed this also when i was creating my patch, but fixed it in a way that works for all adapters https://github.com/influitive/apartment/pull/316/files#diff-3c1648ae31d9d2ce5c1a1ec6dfe2d1d2R126

you'll notice your tests are failing for postgres, etc, because the backtick isn't valid syntax there. i used `conn.quote_table_name(...)` to get the correct escaping mechanism for table names from the underlying adapter.

if you update the PR to this i'm sure it can be merged 👍🏼

**Comment by ironiqu** [comment]
oh...postgres

> if you update your code to this i'm sure it can be merged

thank @mikecmpbll

**Comment by bradrobertson** [comment]
@ironiqu any chance you can fix this up?

**Comment by caironoleto** [comment]
@mikecmpbll this PR can be closed.

**Pull request closed without merging**
