### PR TITLE
Set postgresql environment variables for pg_dump.

### PR DESCRIPTION
**Pull request by MitinPavel**
Apartment::Adapters::PostgresqlSchemaFromSqlAdapter creates SQL dump by executing `pg_dump` utility. Unfortunately the adapter doesn't provide credentials and host/port configuration to `pg_dump` process.

To fix the issue, the pull-request changes the adapter setting PGHOST, PGPORT, PGUSER and PGPASSWORD environment variables if they present in provided config.

### CODE REVIEW

**Comment by bradrobertson** [comment]
Can you squash those commits please?

**Comment by MitinPavel** [comment]
Sure. Will do it.

On Fri, Jan 23, 2015 at 6:08 PM, Brad Robertson <notifications@github.com>
wrote:

> Can you squash those commits please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/influitive/apartment/pull/208#issuecomment-71216297>.
>



-- 
Best regards, Pavel Mitin

**Comment by ndenkowycz** [comment]
+1 I would like to see this merged soon as well.

**Comment by MitinPavel** [comment]
Already squashed.
@bradrobertson please check it.

**Comment by bradrobertson** [comment]
right, sorry for the delay, will release a patch version soon

**Comment by ertejaspatel** [comment]
I am having trouble with pg_dump to work correctly as by default, it picks the current operating system username and run against it which will definitely fail. 

so Is there any updates on this? if not - is there any guide on how to set up this environment variables for pg_dump correctly. 

Any help would be greatly appreciated.

**Comment by bradrobertson** [comment]
Whoops, not sure how I missed this on the last release. Latest version has it now, sorry!

**Comment by ertejaspatel** [comment]
Is there any guide or documentation on how to configure correct credentials to run pg_dump or it will by default take credentials from database.yml?

**Comment by MitinPavel** [comment]
Hello @ertejaspatel  

If you check https://github.com/influitive/apartment/blob/development/lib/apartment/adapters/postgresql_adapter.rb#L176-179 you will see that by default it tries to take credentials from `@config`. And `@config` contains data from `database.yml`.

**Pull request merged**
