### PR TITLE
Test against Ruby head and Rails master

### PR DESCRIPTION
**Pull request by meganemura**
Continued from #217.

Test against ruby-head and rails master branch is better way to keep up to date.

### CODE REVIEW

**Comment by meganemura** [comment]
I forgot to mention @nicolasleger who initially created commits in this PR.
This is not intentionally :bow:

**Comment by mikecmpbll** [comment]
thx!

**Comment by meganemura** [comment]
Ah, squashed commit is authored only me. I should write a description about not to squash commits all to respect pioneer's contribution. I feel bad for @nicolasleger 🙇

**Comment by mikecmpbll** [comment]
my apologies, i should have spotted that. i'll pay closer attention next time ;).

**Pull request merged**
